/*	Vapor API Terms and Conditions
 *
 *  - You MAY NOT
 *  	- attempt to claim ownership of, or pass off the Vapor source code and materials as your own work unless:
 *
 *  		- used as constituent component in an Android application that you intend to release and/or profit from
 *
 *		- use or redistribute the Vapor source code and materials without explicit attribution to the owning parties
 *
 *  	- advertise Vapor in a misleading, inappropriate or offensive fashion
 *
 * - Indemnity
 * 		You agree to indemnify and hold harmless the authors of the Software and any contributors for any direct, indirect, 
 * 		incidental, or consequential third-party claims, actions or suits, as well as any related expenses, liabilities, damages, 
 * 		settlements or fees arising from your use or misuse of the Software, or a violation of any terms of this license.
 *  
 *  - DISCLAIMER OF WARRANTY
 *  	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
 *		WARRANTIES OF QUALITY, PERFORMANCE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 *  
 *  - LIMITATIONS OF LIABILITY
 *  	YOU ASSUME ALL RISK ASSOCIATED WITH THE INSTALLATION AND USE OF THE SOFTWARE. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
 * 		HOLDERS OF THE SOFTWARE BE LIABLE FOR CLAIMS, DAMAGES OR OTHER LIABILITY ARISING FROM, OUT OF, OR IN CONNECTION WITH THE 
 *		SOFTWARE. LICENSE HOLDERS ARE SOLELY RESPONSIBLE FOR DETERMINING THE APPROPRIATENESS OF USE AND ASSUME ALL RISKS ASSOCIATED 
 *		WITH ITS USE, INCLUDING BUT NOT LIMITED TO THE RISKS OF PROGRAM ERRORS, DAMAGE TO EQUIPMENT, LOSS OF DATA OR SOFTWARE PROGRAMS, 
 *		OR UNAVAILABILITY OR INTERRUPTION OF OPERATIONS.
 *  
 *  © Darius Hodaei. License Version 1.1. Last Updated 30/06/2013.
*/

/*This file has been autogenerated by the Vapid Tool v1.0 @ 22/12/2012 22:43:12*/
package vapor.widget;

import java.util.ArrayList;

import android.graphics.drawable.Drawable;
import android.widget.AutoCompleteTextView;
import android.widget.ListAdapter;

/**
 * Fluent variadic Vapor companion to AutoCompleteTextView, an editable text
 * view that shows completion suggestions automatically while the user is
 * typing. The list of suggestions is displayed in a drop down menu from which
 * the user can choose an item to replace the content of the edit box with.
 * 
 * @author Darius H (darius@vapor-api.com)
 * @since 1.0
 * @param <T>
 *            A standard Android type derived from AutoCompleteTextView
 * @param <X>
 *            A Vapor type derived from VaporAutoCompleteTextView
 * @param <self>
 *            A recursively defined type that provides information for fluent
 *            method invocation
 */
public class VaporXAutoCompleteTextView<T extends AutoCompleteTextView, X extends VaporAutoCompleteTextView<T, ?>, self extends VaporXAutoCompleteTextView<T, X, self>>
		extends VaporXEditText<T, X, self> {

	public VaporXAutoCompleteTextView(Integer... ids) {
		super(ids);
	}

	public VaporXAutoCompleteTextView(T... autoCompleteTextViews) {
		super(autoCompleteTextViews);
	}

	public VaporXAutoCompleteTextView(X... vaporAutoCompleteTextViews) {
		super(vaporAutoCompleteTextViews);
	}

	public VaporXAutoCompleteTextView(
			VaporXAutoCompleteTextView<T, X, ?>... vaporXAutoCompleteTextViews) {
		super(vaporXAutoCompleteTextViews);
	}

	public VaporXAutoCompleteTextView(Object... autoCompleteTextViewItems) {
		super(autoCompleteTextViewItems);
	}

	/**
	 * Returns a filterable list adapter used for auto completion.
	 * 
	 * @return a data adapter used for auto completion
	 */
	public ArrayList<ListAdapter> adapter() {
		int _size = this.members.size();
		ArrayList<ListAdapter> _returns = new ArrayList<ListAdapter>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).adapter());
		return _returns;
	}

	/**
	 * Returns the id for the view that the auto-complete drop down list is
	 * anchored to.
	 * 
	 * @return the view's id, or NO_ID if none specified
	 */
	public ArrayList<Integer> popAnchor() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).popAnchor());
		return _returns;
	}

	/**
	 * Sets the view to which the auto-complete drop down list should anchor.
	 * The view corresponding to this id will not be loaded until the next time
	 * it is needed to avoid loading a view which is not yet instantiated.
	 * 
	 * @param id
	 *            the id to anchor the drop down list view to
	 * @return self
	 */
	public self popAnchor(int id) {
		for (X vaporView : members)
			vaporView.popAnchor(id);
		return (self) this;

	}

	/**
	 * Clear the list selection. This may only be temporary, as user input will
	 * often bring it back.
	 * 
	 * @return self
	 */
	public self clearSelection() {
		for (X vaporView : members)
			vaporView.clearSelection();
		return (self) this;

	}

	/**
	 * Performs the text completion by converting the selected item from the
	 * drop down list into a string, replacing the text box's content with this
	 * string and finally dismissing the drop down menu.
	 * 
	 * @return self
	 */
	public self complete() {
		for (X vaporView : members)
			vaporView.complete();
		return (self) this;

	}

	/**
	 * Gets the optional hint text displayed at the bottom of the the matching
	 * list.
	 * 
	 * @return The hint text, if any
	 */
	public ArrayList<CharSequence> completionHint() {
		int _size = this.members.size();
		ArrayList<CharSequence> _returns = new ArrayList<CharSequence>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).completionHint());
		return _returns;
	}

	/**
	 * Sets the optional hint text that is displayed at the bottom of the the
	 * matching list. This can be used as a cue to the user on how to best use
	 * the list, or to provide extra information.
	 * 
	 * @param completionHint
	 *            the text to be displayed to the user
	 * @return self
	 */
	public self completionHint(CharSequence completionHint) {
		for (X vaporView : members)
			vaporView.completionHint(completionHint);
		return (self) this;

	}

	/**
	 * Identifies whether the view is currently performing a text completion, so
	 * subclasses can decide whether to respond to text changed events.
	 * 
	 * @return
	 */
	public ArrayList<Boolean> completing() {
		int _size = this.members.size();
		ArrayList<Boolean> _returns = new ArrayList<Boolean>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).completing());
		return _returns;
	}

	/**
	 * Gets the background of the auto-complete drop-down list.
	 * 
	 * @return the background drawable
	 */
	public ArrayList<Drawable> popBg() {
		int _size = this.members.size();
		ArrayList<Drawable> _returns = new ArrayList<Drawable>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).popBg());
		return _returns;
	}

	/**
	 * Sets the background of the auto-complete drop-down list.
	 * 
	 * @param resId
	 *            the id of the drawable to set as the background
	 * @return self
	 */
	public self popBg(int resId) {
		for (X vaporView : members)
			vaporView.popBg(resId);
		return (self) this;

	}

	/**
	 * Sets the background of the auto-complete drop-down list.
	 * 
	 * @param backgroundDrawable
	 *            the drawable to set as the background
	 * @return self
	 */
	public self popBg(Drawable backgroundDrawable) {
		for (X vaporView : members)
			vaporView.popBg(backgroundDrawable);
		return (self) this;

	}

	/**
	 * Returns the current height for the auto-complete drop down list. This can
	 * be a fixed height, or MATCH_PARENT to fill the screen, or WRAP_CONTENT to
	 * fit the height of the drop down's content.
	 * 
	 * @return the height for the drop down list
	 */
	public ArrayList<Integer> popHeight() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).popHeight());
		return _returns;
	}

	/**
	 * Sets the current height for the auto-complete drop down list. This can be
	 * a fixed height, or MATCH_PARENT to fill the screen, or WRAP_CONTENT to
	 * fit the height of the drop down's content.
	 * 
	 * @param dropDownHeight
	 *            the height to use
	 * @return self
	 */
	public self popHeight(int dropDownHeight) {
		for (X vaporView : members)
			vaporView.popHeight(dropDownHeight);
		return (self) this;

	}

	/**
	 * Gets the horizontal offset used for the auto-complete drop-down list.
	 * 
	 * @return the horizontal offset
	 */
	public ArrayList<Integer> popXOffset() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).popXOffset());
		return _returns;
	}

	/**
	 * Sets the horizontal offset used for the auto-complete drop-down list.
	 * 
	 * @param offset
	 *            the horizontal offset
	 * @return self
	 */
	public self popXOffset(int offset) {
		for (X vaporView : members)
			vaporView.popXOffset(offset);
		return (self) this;

	}

	/**
	 * Indicates whether the popup menu is showing.
	 * 
	 * @return true if the popup menu is showing, false otherwise
	 */
	public ArrayList<Boolean> popShowing() {
		int _size = this.members.size();
		ArrayList<Boolean> _returns = new ArrayList<Boolean>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).popShowing());
		return _returns;
	}

	/**
	 * Sets whether the drop down is showing on screen.
	 * 
	 * @param showDropDown
	 *            true to show the drop down, or false to dismiss it
	 * @return self
	 */
	public self popShowing(boolean showDropDown) {
		for (X vaporView : members)
			vaporView.popShowing(showDropDown);
		return (self) this;

	}

	/**
	 * Gets the vertical offset used for the auto-complete drop-down list.
	 * 
	 * @return the vertical offset
	 */
	public ArrayList<Integer> popYOffset() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).popYOffset());
		return _returns;
	}

	/**
	 * Sets the vertical offset used for the auto-complete drop-down list.
	 * 
	 * @param offset
	 *            the vertical offset
	 * @return self
	 */
	public self popYOffset(int offset) {
		for (X vaporView : members)
			vaporView.popYOffset(offset);
		return (self) this;

	}

	/**
	 * Returns the current width for the auto-complete drop down list. This can
	 * be a fixed width, or MATCH_PARENT to fill the screen, or WRAP_CONTENT to
	 * fit the width of its anchor view.
	 * 
	 * @return the width for the drop down list
	 */
	public ArrayList<Integer> popWidth() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).popWidth());
		return _returns;
	}

	/**
	 * Sets the current width for the auto-complete drop down list. This can be
	 * a fixed width, or MATCH_PARENT to fill the screen, or WRAP_CONTENT to fit
	 * the width of its anchor view.
	 * 
	 * @param width
	 *            the width to use
	 * @return self
	 */
	public self popWidth(int width) {
		for (X vaporView : members)
			vaporView.popWidth(width);
		return (self) this;

	}

	/**
	 * Set a listener that will be invoked whenever the AutoCompleteTextView's
	 * list of completions is dismissed.
	 * 
	 * @param dismissListener
	 *            Listener to invoke when completions are dismissed
	 * @return self
	 */
	public self dismiss(
			vapor.listeners.autocompletetextview.$dismiss dismissListener) {
		for (X vaporView : members)
			vaporView.dismiss(dismissListener);
		return (self) this;

	}

	/**
	 * Returns true if the amount of text in the field meets or exceeds the
	 * threshold() requirement. You can override this to impose a different
	 * standard for when filtering will be triggered.
	 * 
	 * @return true if the amount of text in the field meets or exceeds the
	 *         threshold() requirement
	 */
	public ArrayList<Boolean> enoughToFilter() {
		int _size = this.members.size();
		ArrayList<Boolean> _returns = new ArrayList<Boolean>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).enoughToFilter());
		return _returns;
	}

	/**
	 * Fluent equivalent Vapor method for invoking onFilterComplete(int), which
	 * notifies the end of a filtering operation.
	 * 
	 * @param count
	 *            the number of values computed by the filter
	 * @return self
	 */
	public self filterComplete(int count) {
		for (X vaporView : members)
			vaporView.filterComplete(count);
		return (self) this;

	}

	/**
	 * Sets the listener that will be notified when the user clicks an item in
	 * the drop down list.
	 * 
	 * @param itemClickListener
	 *            the item click listener
	 * @return self
	 */
	public self itemClick(
			vapor.listeners.widget.adapterview.$click itemClickListener) {
		for (X vaporView : members)
			vaporView.itemClick(itemClickListener);
		return (self) this;

	}

	/**
	 * Sets the listener that will be notified when the user selects an item in
	 * the drop down list.
	 * 
	 * @param itemSelectedListener
	 *            the item selected listener
	 * @return self
	 */
	public self itemSelect(
			vapor.listeners.widget.adapterview.$select itemSelectedListener) {
		for (X vaporView : members)
			vaporView.itemSelected(itemSelectedListener);
		return (self) this;

	}

	/**
	 * Get the position of the dropdown view selection, if there is one. Returns
	 * ListView.INVALID_POSITION if there is no dropdown or if there is no
	 * selection.
	 * 
	 * @return the position of the current selection, if there is one, or
	 *         ListView.INVALID_POSITION if not.
	 */
	public ArrayList<Integer> selectedItem() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).selectedItem());
		return _returns;
	}

	/**
	 * Set the position of the dropdown view selection.
	 * 
	 * @param listSelectionPosition
	 *            The position to move the selector to.
	 * @return self
	 */
	public self selectedItem(int listSelectionPosition) {
		for (X vaporView : members)
			vaporView.selectedItem(listSelectionPosition);
		return (self) this;

	}

	/**
	 * Like text(CharSequence), except that it can disable filtering.
	 * 
	 * @param text
	 * @param filter
	 *            If false, no filtering will be performed as a result of this
	 *            call.
	 * @return self
	 */
	public self text(CharSequence text, boolean filter) {
		for (X vaporView : members)
			vaporView.text(text, filter);
		return (self) this;

	}

	/**
	 * Returns the number of characters the user must type before the drop down
	 * list is shown.
	 * 
	 * @return the minimum number of characters to type to show the drop down
	 */
	public ArrayList<Integer> threshold() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).threshold());
		return _returns;
	}

	/**
	 * Specifies the minimum number of characters the user has to type in the
	 * edit box before the drop down list is shown.
	 * 
	 * @param threshold
	 *            the number of characters to type before the drop down is shown
	 * @return self
	 */
	public self threshold(int threshold) {
		for (X vaporView : members)
			vaporView.threshold(threshold);
		return (self) this;

	}

	/**
	 * If a validator was set on this view and the current string is not valid,
	 * ask the validator to fix it.
	 * 
	 * @return self
	 */
	public self validate() {
		for (X vaporView : members)
			vaporView.validate();
		return (self) this;

	}

	/**
	 * Sets the validator used to perform text validation.
	 * 
	 * @param validator
	 *            The validator used to validate the text entered in this
	 *            widget.
	 * @return self
	 */
	public self validator(AutoCompleteTextView.Validator validator) {
		for (X vaporView : members)
			vaporView.validator(validator);
		return (self) this;

	}

}