/*	Vapor API Terms and Conditions
 *
 *  - You MAY NOT
 *  	- attempt to claim ownership of, or pass off the Vapor source code and materials as your own work unless:
 *
 *  		- used as constituent component in an Android application that you intend to release and/or profit from
 *
 *		- use or redistribute the Vapor source code and materials without explicit attribution to the owning parties
 *
 *  	- advertise Vapor in a misleading, inappropriate or offensive fashion
 *
 * - Indemnity
 * 		You agree to indemnify and hold harmless the authors of the Software and any contributors for any direct, indirect, 
 * 		incidental, or consequential third-party claims, actions or suits, as well as any related expenses, liabilities, damages, 
 * 		settlements or fees arising from your use or misuse of the Software, or a violation of any terms of this license.
 *  
 *  - DISCLAIMER OF WARRANTY
 *  	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
 *		WARRANTIES OF QUALITY, PERFORMANCE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 *  
 *  - LIMITATIONS OF LIABILITY
 *  	YOU ASSUME ALL RISK ASSOCIATED WITH THE INSTALLATION AND USE OF THE SOFTWARE. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
 * 		HOLDERS OF THE SOFTWARE BE LIABLE FOR CLAIMS, DAMAGES OR OTHER LIABILITY ARISING FROM, OUT OF, OR IN CONNECTION WITH THE 
 *		SOFTWARE. LICENSE HOLDERS ARE SOLELY RESPONSIBLE FOR DETERMINING THE APPROPRIATENESS OF USE AND ASSUME ALL RISKS ASSOCIATED 
 *		WITH ITS USE, INCLUDING BUT NOT LIMITED TO THE RISKS OF PROGRAM ERRORS, DAMAGE TO EQUIPMENT, LOSS OF DATA OR SOFTWARE PROGRAMS, 
 *		OR UNAVAILABILITY OR INTERRUPTION OF OPERATIONS.
 *  
 *  © Darius Hodaei. License Version 1.1. Last Updated 30/06/2013.
*/

/*This file has been autogenerated by the Vapid Tool v1.0 @ 22/12/2012 22:43:13*/
package vapor.widget;

import java.util.ArrayList;

import vapor.listeners.widget.date.$change;
import android.widget.DatePicker;

/**
 * Fluent variadic Vapor companion to DatePicker, a widget for selecting a date.
 * The date can be selected by a year, month, and day spinners or a
 * CalendarView. The set of spinners and the calendar view are automatically
 * synchronized. The client can customize whether only the spinners, or only the
 * calendar view, or both to be displayed. Also the minimal and maximal date
 * from which dates to be selected can be customized.
 * 
 * @author Darius H (darius@vapor-api.com)
 * @since 1.0
 * @param <T>
 *            A standard Android type derived from DatePicker
 * @param <X>
 *            A Vapor type derived from VaporDatePicker
 * @param <self>
 *            A recursively defined type that provides information for fluent
 *            method invocation
 */
public class VaporXDatePicker<T extends DatePicker, X extends VaporDatePicker<T, ?>, self extends VaporXDatePicker<T, X, self>>
		extends VaporXFrameLayout<T, X, self> {

	public VaporXDatePicker(Integer... ids) {
		super(ids);
	}

	public VaporXDatePicker(T... datePickers) {
		super(datePickers);
	}

	public VaporXDatePicker(X... vaporDatePickers) {
		super(vaporDatePickers);
	}

	public VaporXDatePicker(VaporXDatePicker<T, X, ?>... vaporXDatePickers) {
		super(vaporXDatePickers);
	}

	public VaporXDatePicker(Object... datePickerItems) {
		super(datePickerItems);
	}

	/**
	 * 
	 * @return The selected day of month
	 */
	public ArrayList<Integer> day() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).day());
		return _returns;
	}

	/**
	 * Sets the day
	 * 
	 * @param day
	 *            the value to set the day to
	 * @return self
	 */
	public self day(int dayOfMonth) {
		for (X vaporView : members)
			vaporView.day(dayOfMonth);
		return (self) this;
	}

	/**
	 * Initialize the state. If the provided values designate an inconsistent
	 * date the values are normalized before updating the spinners.
	 * 
	 * @param year
	 *            The initial year.
	 * @param monthOfYear
	 *            The initial month starting from zero.
	 * @param dayOfMonth
	 *            The initial day of the month.
	 * @param dateChangedListener
	 *            How user is notified date is changed by user, can be null.
	 * @return
	 */
	public self init(int year, int monthOfYear, int dayOfMonth,
			$change dateChangedListener) {
		for (X vaporView : members)
			vaporView.init(year, monthOfYear, dayOfMonth, dateChangedListener);
		return (self) this;

	}

	/**
	 * Gets the maximal date supported by this DatePicker in milliseconds since
	 * January 1, 1970 00:00:00 in getDefault() time zone.
	 * 
	 * @return The maximal supported date.
	 */
	public ArrayList<Long> maxDate() {
		int _size = this.members.size();
		ArrayList<Long> _returns = new ArrayList<Long>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).maxDate());
		return _returns;
	}

	/**
	 * Sets the maximal date supported by this DatePicker in milliseconds since
	 * January 1, 1970 00:00:00 in getDefault() time zone.
	 * 
	 * @param maxDate
	 *            The maximal supported date.
	 * @return self
	 */
	public self maxDate(long maxDate) {
		for (X vaporView : members)
			vaporView.maxDate(maxDate);
		return (self) this;

	}

	/**
	 * Gets the minimal date supported by this DatePicker in milliseconds since
	 * January 1, 1970 00:00:00 in getDefault() time zone.
	 * 
	 * @return The minimal supported date.
	 */
	public ArrayList<Long> minDate() {
		int _size = this.members.size();
		ArrayList<Long> _returns = new ArrayList<Long>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).minDate());
		return _returns;
	}

	/**
	 * Sets the minimal date supported by this NumberPicker in milliseconds
	 * since January 1, 1970 00:00:00 in getDefault() time zone.
	 * 
	 * @param minDate
	 *            The minimal supported date.
	 * @return self
	 */
	public self minDate(long minDate) {
		for (X vaporView : members)
			vaporView.minDate(minDate);
		return (self) this;

	}

	/**
	 * 
	 * @return The selected month.
	 */
	public ArrayList<Integer> month() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).month());
		return _returns;
	}

	/**
	 * Sets the month
	 * 
	 * @param month
	 *            the value to set the month to
	 * @return self
	 */
	public self month(int month) {
		for (X vaporView : members)
			vaporView.month(month);
		return (self) this;
	}

	/**
	 * Gets whether the CalendarView is shown.
	 * 
	 * @return True if the calendar view is shown.
	 */
	public ArrayList<Boolean> calendarShowing() {
		int _size = this.members.size();
		ArrayList<Boolean> _returns = new ArrayList<Boolean>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).calendarShowing());
		return _returns;
	}

	/**
	 * Sets whether the CalendarView is shown.
	 * 
	 * @param shown
	 *            True if the calendar view is to be shown.
	 * @return self
	 */
	public self calendarShowing(boolean shown) {
		for (X vaporView : members)
			vaporView.calendarShowing(shown);
		return (self) this;

	}

	/**
	 * Sets whether the spinners are shown.
	 * 
	 * @param shown
	 *            True if the spinners are to be shown.
	 * @return True if the spinners are shown.
	 */
	public self spinnersShowing(boolean shown) {
		for (X vaporView : members)
			vaporView.spinnersShowing(shown);
		return (self) this;

	}

	/**
	 * Gets whether the spinners are shown.
	 * 
	 * @return True if the spinners are shown.
	 */
	public ArrayList<Boolean> spinnersShowing() {
		int _size = this.members.size();
		ArrayList<Boolean> _returns = new ArrayList<Boolean>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).spinnersShowing());
		return _returns;
	}

	/**
	 * Updates the current date.
	 * 
	 * @param year
	 *            Updates the current date.
	 * @param month
	 *            The month which is starting from zero.
	 * @param dayOfMonth
	 *            The day of the month.
	 * @return self
	 */
	public self update(int year, int month, int dayOfMonth) {
		for (X vaporView : members)
			vaporView.update(year, month, dayOfMonth);
		return (self) this;

	}

	/**
	 * 
	 * @return The selected year.
	 */
	public ArrayList<Integer> year() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).year());
		return _returns;
	}

	/**
	 * Sets the year
	 * 
	 * @param year
	 *            the value to set the year to
	 * @return self
	 */
	public self year(int year) {
		for (X vaporView : members)
			vaporView.year(year);
		return (self) this;
	}

}