/*	Vapor API Terms and Conditions
 *
 *  - You MAY NOT
 *  	- attempt to claim ownership of, or pass off the Vapor source code and materials as your own work unless:
 *
 *  		- used as constituent component in an Android application that you intend to release and/or profit from
 *
 *		- use or redistribute the Vapor source code and materials without explicit attribution to the owning parties
 *
 *  	- advertise Vapor in a misleading, inappropriate or offensive fashion
 *
 * - Indemnity
 * 		You agree to indemnify and hold harmless the authors of the Software and any contributors for any direct, indirect, 
 * 		incidental, or consequential third-party claims, actions or suits, as well as any related expenses, liabilities, damages, 
 * 		settlements or fees arising from your use or misuse of the Software, or a violation of any terms of this license.
 *  
 *  - DISCLAIMER OF WARRANTY
 *  	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
 *		WARRANTIES OF QUALITY, PERFORMANCE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 *  
 *  - LIMITATIONS OF LIABILITY
 *  	YOU ASSUME ALL RISK ASSOCIATED WITH THE INSTALLATION AND USE OF THE SOFTWARE. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
 * 		HOLDERS OF THE SOFTWARE BE LIABLE FOR CLAIMS, DAMAGES OR OTHER LIABILITY ARISING FROM, OUT OF, OR IN CONNECTION WITH THE 
 *		SOFTWARE. LICENSE HOLDERS ARE SOLELY RESPONSIBLE FOR DETERMINING THE APPROPRIATENESS OF USE AND ASSUME ALL RISKS ASSOCIATED 
 *		WITH ITS USE, INCLUDING BUT NOT LIMITED TO THE RISKS OF PROGRAM ERRORS, DAMAGE TO EQUIPMENT, LOSS OF DATA OR SOFTWARE PROGRAMS, 
 *		OR UNAVAILABILITY OR INTERRUPTION OF OPERATIONS.
 *  
 *  © Darius Hodaei. License Version 1.1. Last Updated 30/06/2013.
*/

/*This file has been autogenerated by the Vapid Tool v1.0 @ 22/12/2012 22:43:13*/
package vapor.widget;

import java.util.ArrayList;

import android.widget.RadioGroup;

/**
 * Fluent variadic Vapor companion to RadioGroup, used to create a
 * multiple-exclusion scope for a set of radio buttons. Checking one radio
 * button that belongs to a radio group unchecks any previously checked radio
 * button within the same group.
 * 
 * @author Darius H (darius@vapor-api.com)
 * @since 1.0
 * @param <T>
 *            A standard Android type derived from RadioGroup
 * @param <X>
 *            A Vapor type derived from VaporRadioGroup
 * @param <self>
 *            A recursively defined type that provides information for fluent
 *            method invocation
 */
public class VaporXRadioGroup<T extends RadioGroup, X extends VaporRadioGroup<T, ?>, self extends VaporXRadioGroup<T, X, self>>
		extends VaporXLinearLayout<T, X, self> {

	public VaporXRadioGroup(Integer... ids) {
		super(ids);
	}

	public VaporXRadioGroup(T... radioGroups) {
		super(radioGroups);
	}

	public VaporXRadioGroup(X... vaporRadioGroups) {
		super(vaporRadioGroups);
	}

	public VaporXRadioGroup(VaporXRadioGroup<T, X, ?>... vaporXRadioGroups) {
		super(vaporXRadioGroups);
	}

	public VaporXRadioGroup(Object... radioGroupItems) {
		super(radioGroupItems);
	}

	/**
	 * Returns the identifier of the selected radio button in this group. Upon
	 * empty selection, the returned value is -1.
	 * 
	 * @return the unique id of the selected radio button in this group
	 */
	public ArrayList<Integer> itemSelected() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).itemSelected());
		return _returns;
	}

	/**
	 * Sets the selection to the radio button whose identifier is passed in
	 * parameter. Using -1 as the selection identifier clears the selection;
	 * such an operation is equivalent to invoking uncheck().
	 * 
	 * @param id
	 *            the unique id of the radio button to select in this group
	 * @return this
	 */
	public self itemSelected(int id) {
		for (X vaporView : members)
			vaporView.itemSelected(id);
		return (self) this;

	}

	/**
	 * Register a callback to be invoked when the checked radio button changes
	 * in this group.
	 * 
	 * @param checkedChangeListener
	 *            the callback to call on checked state change
	 * @return this
	 */
	public self change(
			vapor.listeners.widget.radiogroup.$checked checkedChangeListener) {
		for (X vaporView : members)
			vaporView.change(checkedChangeListener);
		return (self) this;

	}

	/**
	 * Clears the selection. When the selection is cleared, no radio button in
	 * this group is selected and getCheckedRadioButtonId() returns null.
	 * 
	 * @return
	 */
	public self clear() {
		for (X vaporView : members)
			vaporView.clear();
		return (self) this;

	}

}