/*	Vapor API Terms and Conditions
 *
 *  - You MAY NOT
 *  	- attempt to claim ownership of, or pass off the Vapor source code and materials as your own work unless:
 *
 *  		- used as constituent component in an Android application that you intend to release and/or profit from
 *
 *		- use or redistribute the Vapor source code and materials without explicit attribution to the owning parties
 *
 *  	- advertise Vapor in a misleading, inappropriate or offensive fashion
 *
 * - Indemnity
 * 		You agree to indemnify and hold harmless the authors of the Software and any contributors for any direct, indirect, 
 * 		incidental, or consequential third-party claims, actions or suits, as well as any related expenses, liabilities, damages, 
 * 		settlements or fees arising from your use or misuse of the Software, or a violation of any terms of this license.
 *  
 *  - DISCLAIMER OF WARRANTY
 *  	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
 *		WARRANTIES OF QUALITY, PERFORMANCE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 *  
 *  - LIMITATIONS OF LIABILITY
 *  	YOU ASSUME ALL RISK ASSOCIATED WITH THE INSTALLATION AND USE OF THE SOFTWARE. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
 * 		HOLDERS OF THE SOFTWARE BE LIABLE FOR CLAIMS, DAMAGES OR OTHER LIABILITY ARISING FROM, OUT OF, OR IN CONNECTION WITH THE 
 *		SOFTWARE. LICENSE HOLDERS ARE SOLELY RESPONSIBLE FOR DETERMINING THE APPROPRIATENESS OF USE AND ASSUME ALL RISKS ASSOCIATED 
 *		WITH ITS USE, INCLUDING BUT NOT LIMITED TO THE RISKS OF PROGRAM ERRORS, DAMAGE TO EQUIPMENT, LOSS OF DATA OR SOFTWARE PROGRAMS, 
 *		OR UNAVAILABILITY OR INTERRUPTION OF OPERATIONS.
 *  
 *  © Darius Hodaei. License Version 1.1. Last Updated 30/06/2013.
*/

/*This file has been autogenerated by the Vapid Tool v1.0 @ 22/12/2012 22:43:13*/
package vapor.widget;

import java.util.ArrayList;

import android.widget.NumberPicker;

/**
 * Fluent variadic Vapor companion to NumberPicker, a widget that enables the
 * user to select a number form a predefined range. There are two flavors of
 * this widget and which one is presented to the user depends on the current
 * theme.
 * 
 * @author Darius H (darius@vapor-api.com)
 * @since 1.0
 * @param <T>
 *            A standard Android type derived from NumberPicker
 * @param <X>
 *            A Vapor type derived from VaporNumberPicker
 * @param <self>
 *            A recursively defined type that provides information for fluent
 *            method invocation
 */
public class VaporXNumberPicker<T extends NumberPicker, X extends VaporNumberPicker<T, ?>, self extends VaporXNumberPicker<T, X, self>>
		extends VaporXLinearLayout<T, X, self> {

	public VaporXNumberPicker(Integer... ids) {
		super(ids);
	}

	public VaporXNumberPicker(T... numberPickers) {
		super(numberPickers);
	}

	public VaporXNumberPicker(X... vaporNumberPickers) {
		super(vaporNumberPickers);
	}

	public VaporXNumberPicker(
			VaporXNumberPicker<T, X, ?>... vaporXNumberPickers) {
		super(vaporXNumberPickers);
	}

	public VaporXNumberPicker(Object... numberPickerItems) {
		super(numberPickerItems);
	}

	/**
	 * Gets the values to be displayed instead of string values.
	 * 
	 * @return The displayed values.
	 */
	public ArrayList<String[]> displayVals() {
		int _size = this.members.size();
		ArrayList<String[]> _returns = new ArrayList<String[]>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).displayVals());
		return _returns;
	}

	/**
	 * 
	 * @param displayedValues
	 * @return self
	 */
	public self displayVals(String[] displayedValues) {
		for (X vaporView : members)
			vaporView.displayVals(displayedValues);
		return (self) this;

	}

	/**
	 * Set the formatter to be used for formatting the current value.
	 * 
	 * Note: If you have provided alternative values for the values this
	 * formatter is never invoked.
	 * 
	 * @param formatter
	 *            The formatter object. If formatter is null, valueOf(int) will
	 *            be used.
	 * @return self
	 */
	public self formatter(NumberPicker.Formatter formatter) {
		for (X vaporView : members)
			vaporView.formatter(formatter);
		return (self) this;

	}

	/**
	 * Returns the max value of the picker.
	 * 
	 * @return The max value
	 */
	public ArrayList<Integer> maxVal() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).maxVal());
		return _returns;
	}

	/**
	 * Sets the max value of the picker.
	 * 
	 * @param maxValue
	 *            The max value
	 * @return self
	 */
	public self maxVal(int maxValue) {
		for (X vaporView : members)
			vaporView.maxVal(maxValue);
		return (self) this;

	}

	/**
	 * Returns the min value of the picker.
	 * 
	 * @return The min value
	 */
	public ArrayList<Integer> minVal() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).minVal());
		return _returns;
	}

	/**
	 * Sets the min value of the picker.
	 * 
	 * @param minValue
	 *            The min value
	 * @return self
	 */
	public self minVal(int minValue) {
		for (X vaporView : members)
			vaporView.minVal(minValue);
		return (self) this;

	}

	/**
	 * Set listener to be notified for scroll state changes.
	 * 
	 * @param scrollListener
	 *            The listener.
	 * @return self
	 */
	public self scroll(
			vapor.listeners.widget.numberpicker.$scroll scrollListener) {
		for (X vaporView : members)
			vaporView.scroll(scrollListener);
		return (self) this;

	}

	/**
	 * Sets the speed at which the numbers be incremented and decremented when
	 * the up and down buttons are long pressed respectively.
	 * 
	 * The default value is 300 ms.
	 * 
	 * @param intervalMillis
	 *            The speed (in milliseconds) at which the numbers will be
	 *            incremented and decremented.
	 * @return self
	 */
	public self updateRate(long intervalMillis) {
		for (X vaporView : members)
			vaporView.updateRate(intervalMillis);
		return (self) this;

	}

	/**
	 * Returns the value of the picker.
	 * 
	 * @return The value.
	 */
	public ArrayList<Integer> val() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).val());
		return _returns;
	}

	/**
	 * Set the current value for the number picker.
	 * 
	 * If the argument is less than the minVal() and wraps() is false the
	 * current value is set to the getMinValue() value.
	 * 
	 * If the argument is less than the minVal() and wraps() is true the current
	 * value is set to the getMaxValue() value.
	 * 
	 * If the argument is less than the maxVal() and wraps() is false the
	 * current value is set to the getMaxValue() value.
	 * 
	 * If the argument is less than the maxVal() and wraps() is true the current
	 * value is set to the getMinValue() value.
	 * 
	 * @param value
	 *            The current value.
	 * @return self
	 */
	public self val(int value) {
		for (X vaporView : members)
			vaporView.val(value);
		return (self) this;

	}

	/**
	 * Sets the listener to be notified on change of the current value.
	 * 
	 * @param valueChangedListener
	 *            The listener.
	 * @return self
	 */
	public self val(
			vapor.listeners.widget.numberpicker.$change valueChangedListener) {
		for (X vaporView : members)
			vaporView.val(valueChangedListener);
		return (self) this;

	}

	/**
	 * Gets whether the selector wheel wraps when reaching the min/max value.
	 * 
	 * @return True if the selector wheel wraps.
	 */
	public ArrayList<Boolean> wraps() {
		int _size = this.members.size();
		ArrayList<Boolean> _returns = new ArrayList<Boolean>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).wraps());
		return _returns;
	}

	/**
	 * Sets whether the selector wheel shown during flinging/scrolling should
	 * wrap around the minVal() and maxVal() values.
	 * 
	 * By default if the range (max - min) is more than the number of items
	 * shown on the selector wheel the selector wheel wrapping is enabled.
	 * 
	 * Note: If the number of items, i.e. the range ( maxVal() - minVal()) is
	 * less than the number of items shown on the selector wheel, the selector
	 * wheel will not wrap. Hence, in such a case calling this method is a NOP.
	 * 
	 * @param wrapSelectorWheel
	 *            Whether to wrap.
	 * @return self
	 */
	public self wraps(boolean wrapSelectorWheel) {
		for (X vaporView : members)
			vaporView.wraps(wrapSelectorWheel);
		return (self) this;

	}

}