/*	Vapor API Terms and Conditions
 *
 *  - You MAY NOT
 *  	- attempt to claim ownership of, or pass off the Vapor source code and materials as your own work unless:
 *
 *  		- used as constituent component in an Android application that you intend to release and/or profit from
 *
 *		- use or redistribute the Vapor source code and materials without explicit attribution to the owning parties
 *
 *  	- advertise Vapor in a misleading, inappropriate or offensive fashion
 *
 * - Indemnity
 * 		You agree to indemnify and hold harmless the authors of the Software and any contributors for any direct, indirect, 
 * 		incidental, or consequential third-party claims, actions or suits, as well as any related expenses, liabilities, damages, 
 * 		settlements or fees arising from your use or misuse of the Software, or a violation of any terms of this license.
 *  
 *  - DISCLAIMER OF WARRANTY
 *  	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
 *		WARRANTIES OF QUALITY, PERFORMANCE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 *  
 *  - LIMITATIONS OF LIABILITY
 *  	YOU ASSUME ALL RISK ASSOCIATED WITH THE INSTALLATION AND USE OF THE SOFTWARE. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
 * 		HOLDERS OF THE SOFTWARE BE LIABLE FOR CLAIMS, DAMAGES OR OTHER LIABILITY ARISING FROM, OUT OF, OR IN CONNECTION WITH THE 
 *		SOFTWARE. LICENSE HOLDERS ARE SOLELY RESPONSIBLE FOR DETERMINING THE APPROPRIATENESS OF USE AND ASSUME ALL RISKS ASSOCIATED 
 *		WITH ITS USE, INCLUDING BUT NOT LIMITED TO THE RISKS OF PROGRAM ERRORS, DAMAGE TO EQUIPMENT, LOSS OF DATA OR SOFTWARE PROGRAMS, 
 *		OR UNAVAILABILITY OR INTERRUPTION OF OPERATIONS.
 *  
 *  © Darius Hodaei. License Version 1.1. Last Updated 30/06/2013.
*/

/*This file has been autogenerated by the Vapid Tool v1.0 @ 22/12/2012 22:43:14*/
package vapor.widget;

import java.util.ArrayList;

import vapor.view.VaporXSurfaceView;
import android.net.Uri;
import android.widget.MediaController;
import android.widget.VideoView;

/**
 * Fluent variadic Vapor companion to VideoView, that displays a video file. The
 * VideoView class can load images from various sources (such as resources or
 * content providers), takes care of computing its measurement from the video so
 * that it can be used in any layout manager, and provides various display
 * options such as scaling and tinting.
 * 
 * @author Darius H (darius@vapor-api.com)
 * @since 1.0
 * @param <T>
 *            A standard Android type derived from VideoView
 * @param <X>
 *            A Vapor type derived from VaporVideoView
 * @param <self>
 *            A recursively defined type that provides information for fluent
 *            method invocation
 */
public class VaporXVideoView<T extends VideoView, X extends VaporVideoView<T, ?>, self extends VaporXVideoView<T, X, self>>
		extends VaporXSurfaceView<T, X, self> {

	public VaporXVideoView(Integer... ids) {
		super(ids);
	}

	public VaporXVideoView(T... videoViews) {
		super(videoViews);
	}

	public VaporXVideoView(X... vaporVideoViews) {
		super(vaporVideoViews);
	}

	public VaporXVideoView(VaporXVideoView<T, X, ?>... vaporXVideoViews) {
		super(vaporXVideoViews);
	}

	public VaporXVideoView(Object... videoViewItems) {
		super(videoViewItems);
	}

	/**
	 * 
	 * @return
	 */
	public ArrayList<Integer> bufferPercentage() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).bufferPercentage());
		return _returns;
	}

	/**
	 * Register a callback to be invoked when the end of a media file has been
	 * reached during playback.
	 * 
	 * @param completionListener
	 *            The callback that will be run
	 * @return self
	 */
	public self completion(
			vapor.listeners.media.mediaplayer.$completion completionListener) {
		for (X vaporView : members)
			vaporView.completion(completionListener);
		return (self) this;

	}

	/**
	 * 
	 * @param mediaController
	 * @return self
	 */
	public self controller(MediaController mediaController) {
		for (X vaporView : members)
			vaporView.controller(mediaController);
		return (self) this;

	}

	public ArrayList<Integer> duration() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).duration());
		return _returns;
	}

	/**
	 * Register a callback to be invoked when an error occurs during playback or
	 * setup. If no listener is specified, or if the listener returned false,
	 * VideoView will inform the user of any errors.
	 * 
	 * @param errorListener
	 *            The callback that will be run
	 * @return self
	 */
	public self error(vapor.listeners.media.mediaplayer.$error errorListener) {
		for (X vaporView : members)
			vaporView.error(errorListener);
		return (self) this;

	}

	/**
	 * Register a callback to be invoked when an informational event occurs
	 * during playback or setup.
	 * 
	 * @param infoListener
	 *            The callback that will be run
	 * @return self
	 */
	public self info(vapor.listeners.media.mediaplayer.$info infoListener) {
		for (X vaporView : members)
			vaporView.info(infoListener);
		return (self) this;

	}

	/**
	 * Register a callback to be invoked when the media file is loaded and ready
	 * to go.
	 * 
	 * @param preparedListener
	 *            The callback that will be run
	 * @return self
	 */
	public self prepared(
			vapor.listeners.media.mediaplayer.$prepared preparedListener) {
		for (X vaporView : members)
			vaporView.prepared(preparedListener);
		return (self) this;

	}

	/**
	 * 
	 * @return self
	 */
	public self path(String videoPath) {
		for (X vaporView : members)
			vaporView.path(videoPath);
		return (self) this;

	}

	/**
	 * 
	 * @return self
	 */
	public self paused(boolean paused) {
		for (X vaporView : members)
			vaporView.paused(paused);
		return (self) this;

	}

	/**
	 * 
	 * @return
	 */
	public ArrayList<Boolean> pauseable() {
		int _size = this.members.size();
		ArrayList<Boolean> _returns = new ArrayList<Boolean>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).pauseable());
		return _returns;
	}

	/**
	 * 
	 * @return self
	 */
	public self playing(boolean playing) {
		for (X vaporView : members)
			vaporView.playing(playing);
		return (self) this;

	}

	/**
	 * 
	 * @return
	 */
	public ArrayList<Boolean> playing() {
		int _size = this.members.size();
		ArrayList<Boolean> _returns = new ArrayList<Boolean>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).playing());
		return _returns;
	}

	/**
	 * 
	 * @param desiredSize
	 * @param measureSpec
	 * @return
	 */
	public ArrayList<Integer> resolveAdj(int desiredSize, int measureSpec) {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).resolveAdj(desiredSize,
					measureSpec));
		return _returns;
	}

	/**
	 * 
	 * @return self
	 */
	public self resume() {
		for (X vaporView : members)
			vaporView.resume();
		return (self) this;

	}

	/**
	 * 
	 * @return the current position of the video
	 */
	public ArrayList<Integer> seek() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).seek());
		return _returns;
	}

	/**
	 * 
	 * @param milliseconds
	 * @return self
	 */
	public self seek(int milliseconds) {
		for (X vaporView : members)
			vaporView.seek(milliseconds);
		return (self) this;

	}

	/**
	 * 
	 * @return
	 */
	public ArrayList<Boolean> seekableBackward() {
		int _size = this.members.size();
		ArrayList<Boolean> _returns = new ArrayList<Boolean>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).seekableBackward());
		return _returns;
	}

	/**
	 * 
	 * @return
	 */
	public ArrayList<Boolean> seekableForward() {
		int _size = this.members.size();
		ArrayList<Boolean> _returns = new ArrayList<Boolean>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).seekableForward());
		return _returns;
	}

	/**
	 * 
	 * @return self
	 */
	public self suspend() {
		for (X vaporView : members)
			vaporView.suspend();
		return (self) this;

	}

	/**
	 * 
	 * @return self
	 */
	public self uri(Uri videoUri) {
		for (X vaporView : members)
			vaporView.uri(videoUri);
		return (self) this;

	}

}