/*	Vapor API Terms and Conditions
 *
 *  - You MAY NOT
 *  	- attempt to claim ownership of, or pass off the Vapor source code and materials as your own work unless:
 *
 *  		- used as constituent component in an Android application that you intend to release and/or profit from
 *
 *		- use or redistribute the Vapor source code and materials without explicit attribution to the owning parties
 *
 *  	- advertise Vapor in a misleading, inappropriate or offensive fashion
 *
 * - Indemnity
 * 		You agree to indemnify and hold harmless the authors of the Software and any contributors for any direct, indirect, 
 * 		incidental, or consequential third-party claims, actions or suits, as well as any related expenses, liabilities, damages, 
 * 		settlements or fees arising from your use or misuse of the Software, or a violation of any terms of this license.
 *  
 *  - DISCLAIMER OF WARRANTY
 *  	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
 *		WARRANTIES OF QUALITY, PERFORMANCE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 *  
 *  - LIMITATIONS OF LIABILITY
 *  	YOU ASSUME ALL RISK ASSOCIATED WITH THE INSTALLATION AND USE OF THE SOFTWARE. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
 * 		HOLDERS OF THE SOFTWARE BE LIABLE FOR CLAIMS, DAMAGES OR OTHER LIABILITY ARISING FROM, OUT OF, OR IN CONNECTION WITH THE 
 *		SOFTWARE. LICENSE HOLDERS ARE SOLELY RESPONSIBLE FOR DETERMINING THE APPROPRIATENESS OF USE AND ASSUME ALL RISKS ASSOCIATED 
 *		WITH ITS USE, INCLUDING BUT NOT LIMITED TO THE RISKS OF PROGRAM ERRORS, DAMAGE TO EQUIPMENT, LOSS OF DATA OR SOFTWARE PROGRAMS, 
 *		OR UNAVAILABILITY OR INTERRUPTION OF OPERATIONS.
 *  
 *  © Darius Hodaei. License Version 1.1. Last Updated 30/06/2013.
*/

/*This file has been autogenerated by the Vapid Tool v1.0 @ 22/12/2012 22:43:13*/
package vapor.widget;

import java.util.ArrayList;

import android.widget.GridView;
import android.widget.ListAdapter;

/**
 * Fluent variadic Vapor companion to GridView, a view that shows items in
 * two-dimensional scrolling grid. The items in the grid come from the
 * ListAdapter associated with this view.
 * 
 * @author Darius H (darius@vapor-api.com)
 * @since 1.0
 * @param <T>
 *            A standard Android type derived from GridView
 * @param <X>
 *            A Vapor type derived from VaporGridView
 * @param <self>
 *            A recursively defined type that provides information for fluent
 *            method invocation
 */
public class VaporXGridView<T extends GridView, X extends VaporGridView<T, ?>, self extends VaporXGridView<T, X, self>>
		extends VaporXAbsListView<T, X, self> {

	public VaporXGridView(Integer... ids) {
		super(ids);
	}

	public VaporXGridView(T... gridViews) {
		super(gridViews);
	}

	public VaporXGridView(X... vaporGridViews) {
		super(vaporGridViews);
	}

	public VaporXGridView(VaporXGridView<T, X, ?>... vaporXGridViews) {
		super(vaporXGridViews);
	}

	public VaporXGridView(Object... gridViewItems) {
		super(gridViewItems);
	}

	/**
	 * Returns the adapter currently associated with this widget.
	 * 
	 * @return The adapter used to provide this view's content.
	 */
	public ArrayList<ListAdapter> adapter() {
		int _size = this.members.size();
		ArrayList<ListAdapter> _returns = new ArrayList<ListAdapter>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).adapter());
		return _returns;
	}

	public self adapter(ListAdapter adapter) {
		for (X vaporView : members)
			vaporView.adapter(adapter);
		return (self) this;

	}

	/**
	 * Get the number of columns in the grid. Returns AUTO_FIT if the Grid has
	 * never been laid out.
	 * 
	 * @return
	 */
	public ArrayList<Integer> cols() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).cols());
		return _returns;
	}

	public self cols(int numberOfColumns) {
		for (X vaporView : members)
			vaporView.cols(numberOfColumns);
		return (self) this;

	}

	/**
	 * Return the width of a column in the grid.
	 * 
	 * This may not be valid yet if a layout is pending.
	 * 
	 * @return The column width in pixels
	 */
	public ArrayList<Integer> colWidth() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).colWidth());
		return _returns;
	}

	/**
	 * Set the width of columns in the grid.
	 * 
	 * @param columnWidth
	 *            The column width, in pixels.
	 * @return this
	 */
	public self colWidth(int columnWidth) {
		for (X vaporView : members)
			vaporView.colWidth(columnWidth);
		return (self) this;

	}

	/**
	 * Describes how the child views are horizontally aligned. Defaults to
	 * Gravity.LEFT
	 * 
	 * @return the gravity that will be applied to this grid's children
	 */
	public ArrayList<Integer> gravity() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).gravity());
		return _returns;
	}

	/**
	 * Set the gravity for this grid. Gravity describes how the child views are
	 * horizontally aligned. Defaults to Gravity.LEFT
	 * 
	 * @param gravity
	 *            the gravity to apply to this grid's children
	 * @return this
	 */
	public self gravity(int gravity) {
		for (X vaporView : members)
			vaporView.gravity(gravity);
		return (self) this;

	}

	/**
	 * Returns the amount of horizontal spacing currently used between each item
	 * in the grid.
	 * 
	 * @return Current horizontal spacing between each item in pixels
	 */
	public ArrayList<Integer> xSpacing() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).xSpacing());
		return _returns;
	}

	/**
	 * Set the amount of horizontal (x) spacing to place between each item in
	 * the grid.
	 * 
	 * @param horizontalSpacing
	 *            The amount of horizontal space between items, in pixels.
	 * @return this
	 */
	public self xSpacing(int horizontalSpacing) {
		for (X vaporView : members)
			vaporView.xSpacing(horizontalSpacing);
		return (self) this;

	}

	/**
	 * Return the requested width of a column in the grid.
	 * 
	 * @return The requested column width in pixels
	 */
	public ArrayList<Integer> reqdColWidth() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).reqdColWidth());
		return _returns;
	}

	/**
	 * Returns the requested amount of horizontal spacing between each item in
	 * the grid.
	 * 
	 * @return The currently requested horizontal spacing between items, in
	 *         pixels
	 */
	public ArrayList<Integer> reqdXSpacing() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).reqdXSpacing());
		return _returns;
	}

	public self itemSelected(int position) {
		for (X vaporView : members)
			vaporView.itemSelected(position);
		return (self) this;

	}

	/**
	 * Smoothly scroll to the specified adapter position offset. The view will
	 * scroll such that the indicated position is displayed.
	 * 
	 * @param offset
	 *            The amount to offset from the adapter position to scroll to.
	 * @return this
	 */
	public self smoothByOffset(int offset) {
		for (X vaporView : members)
			vaporView.smoothByOffset(offset);
		return (self) this;

	}

	/**
	 * 
	 * @return
	 */
	public ArrayList<Integer> stretchMode() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).stretchMode());
		return _returns;
	}

	/**
	 * Control how items are stretched to fill their space.
	 * 
	 * @param stretchMode
	 *            Either NO_STRETCH, STRETCH_SPACING, STRETCH_SPACING_UNIFORM,
	 *            or STRETCH_COLUMN_WIDTH.
	 * @return this
	 */
	public self stretchMode(int stretchMode) {
		for (X vaporView : members)
			vaporView.stretchMode(stretchMode);
		return (self) this;

	}

	/**
	 * Returns the amount of vertical spacing between each item in the grid.
	 * 
	 * @return The vertical spacing between items in pixels
	 */
	public ArrayList<Integer> ySpacing() {
		int _size = this.members.size();
		ArrayList<Integer> _returns = new ArrayList<Integer>(_size);
		for (int _index = 0; _index < _size; _index++)
			_returns.add(this.members.get(_index).ySpacing());
		return _returns;
	}

	/**
	 * Set the amount of vertical (y) spacing to place between each item in the
	 * grid.
	 * 
	 * @param verticalSpacing
	 *            The amount of vertical space between items, in pixels.
	 * @return this
	 */
	public self ySpacing(int verticalSpacing) {
		for (X vaporView : members)
			vaporView.ySpacing(verticalSpacing);
		return (self) this;

	}

}